/**
 * Writes deploy/aws/template.yaml with the compiled proxy inlined as the Lambda function's
 * source, so "Launch Stack" needs no build, no bucket and no container registry.
 *
 * There is only ever one copy of the proxy logic: this reads the tsc output of
 * src/server/handler.ts and src/server/lambda.ts and rewrites the two ES modules into the
 * one CommonJS script CloudFormation expects. Run it after npm run build:
 *
 *   node deploy/aws/generate-template.ts            write the template
 *   node deploy/aws/generate-template.ts --check     fail if the committed template is stale
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");
const templatePath = path.join(here, "template.yaml");

/**
 * "If you include your function source inline with this parameter, AWS CloudFormation
 * places it in a file named index and zips it to create a deployment package. This zip
 * file cannot exceed 4MB."
 * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html
 */
const MAX_INLINE_BYTES = 4 * 1024 * 1024;

const BANNER = [
  "// Generated from src/server/handler.ts and src/server/lambda.ts by",
  "// deploy/aws/generate-template.ts. Do not edit this copy: edit the TypeScript, run",
  "// npm run build, then run the generator again.",
  "//",
  "// CloudFormation stores inline code in a file named index with no extension, which Node",
  "// reads as CommonJS, so the two ES modules are rewritten into one script below.",
].join("\n");

/** Rewrites one tsc emitted ES module into a fragment of a single CommonJS script. */
function toCommonJs(source: string, file: string): string {
  const kept: string[] = [];
  for (const line of source.split("\n")) {
    if (/^import\s/.test(line)) {
      // Everything is concatenated into one script, so cross file imports are dropped.
      if (!line.trimEnd().endsWith(";")) {
        throw new Error(`${file}: this generator cannot inline a multi line import: ${line}`);
      }
      continue;
    }
    if (/^export default \w+;$/.test(line)) continue;
    if (/^export\s/.test(line)) {
      kept.push(line.replace(/^export\s/, ""));
      continue;
    }
    if (/^\s+(import|export)\s/.test(line)) {
      throw new Error(`${file}: this generator cannot inline an indented import or export: ${line}`);
    }
    kept.push(line);
  }
  const rewritten = kept.join("\n");
  if (/(^|\n)\s*(import|export)[\s(]/.test(rewritten)) {
    throw new Error(`${file}: an import or export survived the rewrite`);
  }
  return rewritten.trim();
}

async function readBuilt(relative: string): Promise<string> {
  const file = path.join(repoRoot, relative);
  try {
    return await fs.readFile(file, "utf8");
  } catch (error) {
    const err = error as NodeJS.ErrnoException;
    throw new Error(`could not read ${file} (${err.code ?? err.message}). Run npm run build first.`);
  }
}

export async function buildInlineCode(): Promise<string> {
  const handler = toCommonJs(await readBuilt("dist/server/handler.js"), "dist/server/handler.js");
  const lambda = toCommonJs(await readBuilt("dist/server/lambda.js"), "dist/server/lambda.js");
  const code = [BANNER, "", handler, "", lambda, "", "exports.handler = handler;", ""].join("\n");
  const size = Buffer.byteLength(code, "utf8");
  if (size > MAX_INLINE_BYTES) {
    throw new Error(
      `the inlined function is ${size} bytes, over CloudFormation's ${MAX_INLINE_BYTES} byte inline limit`,
    );
  }
  return code;
}

function indent(code: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return code
    .split("\n")
    .map((line) => (line.trim().length === 0 ? "" : `${pad}${line}`))
    .join("\n");
}

export function renderTemplate(code: string): string {
  return `AWSTemplateFormatVersion: "2010-09-09"

# Generated by deploy/aws/generate-template.ts. Do not edit by hand.
Description: >-
  stop-rules team server: a locked down proxy for Jev and the OpenAI judge behind one Lambda
  function URL, so no developer needs an API key.

Parameters:
  TypesafeApiKey:
    Type: String
    NoEcho: true
    MinLength: 1
    Description: >-
      Your Jev API key from TypeSafe. It stays in this function's configuration and is
      never sent to a developer.
  StopRulesToken:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: >-
      The token every developer's hook will send. Generate one with: openssl rand -hex 24
  OpenAiApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: >-
      Your OpenAI API key. Leave it empty unless your repos use the openai judge.

Resources:
  StopRulesRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StopRulesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: stop-rules team server
      Runtime: nodejs22.x
      Handler: index.handler
      MemorySize: 256
      Timeout: 70
      Role: !GetAtt StopRulesRole.Arn
      Environment:
        Variables:
          TYPESAFE_API_KEY: !Ref TypesafeApiKey
          STOP_RULES_TOKEN: !Ref StopRulesToken
          OPENAI_API_KEY: !Ref OpenAiApiKey
      Code:
        ZipFile: |
${indent(code, 10)}

  StopRulesUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt StopRulesFunction.Arn
      AuthType: NONE

  # From October 2025 a public function URL needs both of these.
  StopRulesInvokeUrl:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt StopRulesFunction.Arn
      FunctionUrlAuthType: NONE
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  StopRulesInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt StopRulesFunction.Arn
      FunctionUrlAuthType: NONE
      Action: lambda:InvokeFunction
      Principal: "*"

Outputs:
  Endpoint:
    Description: Give this to your team, then run stop-rules team <endpoint> in each repo.
    Value: !GetAtt StopRulesUrl.FunctionUrl
  Health:
    Description: Open this in a browser to see whether the server is configured.
    Value: !Sub "\${StopRulesUrl.FunctionUrl}health"
`;
}

async function main(argv: readonly string[]): Promise<number> {
  const check = argv.includes("--check");
  const unknown = argv.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`generate-template: unknown argument ${unknown[0] ?? ""}\n`);
    return 1;
  }
  const rendered = renderTemplate(await buildInlineCode());
  if (check) {
    let existing = "";
    try {
      existing = await fs.readFile(templatePath, "utf8");
    } catch (error) {
      const err = error as NodeJS.ErrnoException;
      process.stderr.write(`generate-template: could not read ${templatePath}: ${err.code ?? err.message}\n`);
      return 1;
    }
    if (existing !== rendered) {
      process.stderr.write(
        `generate-template: ${templatePath} is stale. Run: node deploy/aws/generate-template.ts\n`,
      );
      return 1;
    }
    process.stdout.write(`${templatePath} is up to date\n`);
    return 0;
  }
  await fs.writeFile(templatePath, rendered, "utf8");
  process.stdout.write(
    `wrote ${templatePath} (${Buffer.byteLength(rendered, "utf8")} bytes total)\n`,
  );
  return 0;
}

main(process.argv.slice(2)).then(
  (code) => {
    process.exitCode = code;
  },
  (error: unknown) => {
    process.stderr.write(
      `generate-template: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  },
);
